name: Crypto Dust Scanner
on:
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - setup-python: '3.9'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}
          BSCSCAN_API: ${{ secrets.BSCSCAN_API }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
